### ISSUE TITLE
[Feature] Setup Guide for project

### ISSUE THREAD

**Issue by Nitinshukla88** [JAYESHBATRA/Virtuo-Learn#105]
### Description

There should be a proper setup guide provided in this project to how to run this project locally.

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea 
- [ ] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor
- [ ] I am an IWOC 2.0 contributor

**Comment by Bhupendra3444** [comment]
hey @JAYESHBATRA please assign me this issue under iwoc.
