### ISSUE TITLE
Feature Request: Add Working Links in Features Section for better User Experience 

### ISSUE THREAD

**Issue by NaveenChandraAdhikari** [JAYESHBATRA/Virtuo-Learn#107]
### Description

This feature request aims to significantly improve user experience by incorporating functional links for actions such as watching videos, accessing simulations, experiencing 3D visualizations, and resolving doubts.

### Screenshots

![Screenshot from 2024-01-12 03-09-55](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/44281971/32e5c52c-f0c8-4aa6-9150-a3ee7a5b6c34)

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea 
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor
- [x] I am an IWOC 2.0 contributor

**Comment by Bhupendra3444** [comment]
hey @JAYESHBATRA please assign me this issue under iwoc.
