### ISSUE TITLE
[BUG] Icons overlapping the Text in the mobile view.

### ISSUE THREAD

**Issue by Tholkappiar** [JAYESHBATRA/Virtuo-Learn#113]
### Issue Title:
Improve Mobile View: Move Social Media Icons to Footer

### Description:
When accessing the website on a mobile device, the social media icons overlap with the text, impacting the user experience. I propose relocating the social media icons to the footer to enhance the mobile view and avoid interference with the main content.

### Problem:
The social media icons are currently positioned in a way that they overlap with the text on the mobile view, making it difficult for users to read the content.

### Proposed Solution:
Move the social media icons to the footer of the website to ensure they don't interfere with the main content on the mobile view. This adjustment will enhance the user experience and maintain a clean and organized layout.

### Screenshots:
![Screenshot from 2024-01-13 16-15-02](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/114584730/0d365dc2-c6df-45c5-bdf0-7513c842ef60)

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea
- [X] I am willing to work on this issue (optional)
- [ ] I am a SWOC'24 contributor
- [X] I am an IWOC 2.0 contributor

**Comment by Bhupendra3444** [comment]
hey @JAYESHBATRA please assign me this issue under iwoc.

**Comment by DrishnaTrivedi** [comment]
@JAYESHBATRA please assign this issue to me under GSSoC. I can contribute effectively.
