### ISSUE TITLE
[BUG] Sliders not in Sync With Text

### ISSUE THREAD

**Issue by JiyaGupta-cs** [JAYESHBATRA/Virtuo-Learn#118]
### Description

The text labels of the sliders are not with the sliders because the function position() used in this code to place the slider works differently with the text() function  

**Page-**
Collision Page under Simulations

**Proposed Solution-**
**=>** We can't do it by CSS.
**=>** It can be done by making the both the things work by using the same function using P5.JS
**=>** Moreover, we could not change the position values in slider.position(width, height); manually because the top and left (x,y) indexes would vary with each mobile device
**=>** Therefore I fixed the issue using a different approach.

### Screenshots

**Desktop View -**

![image](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/140608790/c935844b-b54b-4cde-b3fe-27effeb8e5cb)

**Mobile View -**

![image](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/140608790/c39c1c66-e030-420a-9a4a-a61c6eb35594)

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea
- [X] I am willing to work on this issue (optional)
- [ ] I am a SWOC'24 contributor
- [X] I am an IWOC 2.0 contributor

**Comment by JiyaGupta-cs** [comment]
@JAYESHBATRA Please assign me this issue under IWOC. Also Please add the labels "medium/hard" along with "iwoc2024" to the issue.

**Comment by Bhupendra3444** [comment]
hey @JAYESHBATRA please assign me this issue under iwoc.

**Comment by JiyaGupta-cs** [comment]
@Bhupendra3444 
I have already made the PR on this issue which was raised by me
You can look for other issues 👍
