### ISSUE TITLE
ICON overlapping and text

### ISSUE THREAD

**Issue by tushargupta1504** [JAYESHBATRA/Virtuo-Learn#121]
### Description

The webiste is very unstable for mobile user the icon are overlapping with text and many more

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor
- [X] I am an IWOC 2.0 contributor

**Comment by Tholkappiar** [comment]
Hey contributor , i have already addressed this issue in #113 .

**Comment by Bhupendra3444** [comment]
hey @JAYESHBATRA please assign me this issue under iwoc.
