### ISSUE TITLE
[Feature]  A login or sign up button  is also there for the user ,so that they can access their own content seperately.

### ISSUE THREAD

**Issue by shivam101203** [JAYESHBATRA/Virtuo-Learn#127]
### Description

 A sign up button is needed so that a user can have his /her personalised course .It will make the site good and user can get their study content easily.

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea 
- [ ] I am willing to work on this issue (optional)
- [ ] I am a SWOC'24 contributor
- [X] I am an IWOC 2.0 contributor

**Comment by shivam101203** [comment]
please assign this issue to me under iwoc2024 @JAYESHBATRA

**Comment by JAYESHBATRA** [comment]
@shivam101203 Will you implement the complete Login/SignUp functionality or will just add frontend ?

**Comment by shivam101203** [comment]
sir i will just add the front  end because i did not have backend experience at all

**Comment by JAYESHBATRA** [comment]
No need.

**Comment by shivam101203** [comment]
Okk sir
