### ISSUE TITLE
Create a page where students can have their doubt solved.

### ISSUE THREAD

**Issue by shivam101203** [JAYESHBATRA/Virtuo-Learn#138]
### Description

Student can solve his/her doubt by using  doubt engine

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea 
- [X] I am willing to work on this issue (optional)
- [ ] I am a SWOC'24 contributor
- [X] I am an IWOC 2.0 contributor

**Comment by shivam101203** [comment]
Please assign issue to me under iwoc 2025 @JAYESH-BATRA

**Comment by JAYESHBATRA** [comment]
@shivam101203 Duplicate Issue
