### ISSUE TITLE
[Feature] Enhancement of Home Page in Dark mode

### ISSUE THREAD

**Issue by Nitinshukla88** [JAYESHBATRA/Virtuo-Learn#144]
### Description

When we enable dark mode on on home page, then some styles are not properly set for example the project title is black in color initially. When we set dark mode then it disappears. Also the home is having purple color initially and with dark mode, it doesn't appears appealing and some many more mistakes.

### Screenshots

![Screenshot (12)](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/143546627/e6a9fd75-56f9-4c79-a7c5-5c8637c8cf84)
![Screenshot (11)](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/143546627/ca95c4ab-94ae-4a3a-8689-e2a07c390bc4)

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea 
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor
- [ ] I am an IWOC 2.0 contributor

**Comment by Nitinshukla88** [comment]
Approve the issue and and assign it to me @JAYESH-BATRA

**Comment by ayush-that** [comment]
@JAYESHBATRA please merge the pull request, the issue has been resolved.

**Comment by Nitinshukla88** [comment]
To @JAYESHBATRA @ayush-that 
Please take a careful look at website in dark mode, the potential issues which I mentioned have not been resolved completely yet.
Hey @ayush-that In Dark mode, make the white text first in home button and over hovering put css to make it blue like the same buttons and for the up arrow make the arrow black when it is hovered. I hope you are getting my point.

**Comment by ayush-that** [comment]
> To @JAYESHBATRA @ayush-that Please take a careful look at website in dark mode, the potential issues which I mentioned have not been resolved completely yet. Hey @ayush-that In Dark mode, make the white text first in home button and over hovering put css to make it blue like the same buttons and for the up arrow make the arrow black when it is hovered. I hope you are getting my point.

I'll do that, thanks for bringing it to my notice
