### ISSUE TITLE
[Feature] Question Count in Quiz

### ISSUE THREAD

**Issue by JiyaGupta-cs** [JAYESHBATRA/Virtuo-Learn#153]
### Description

The question number is not shown on the question card in the quiz.
It leads to confusion for the user about how many questions are left and how many has he attempted.
Therefore, the question number needs to be displayed along with the current question count, the total number of questions, and the number of questions attempted.

### Screenshots

![image](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/140608790/088b2bd1-6583-4329-a7fc-0c7a27c90e6e)

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea 
- [X] I am willing to work on this issue (optional)
- [ ] I am a SWOC'24 contributor
- [X] I am an IWOC 2.0 contributor

**Comment by JAYESHBATRA** [comment]
Make sure you make the changes for all the quizzes and not just for one quiz.

**Comment by JiyaGupta-cs** [comment]
@JAYESHBATRA 
I will do it for all the quizzes
Can you pz add the hard label to it
Since it would take ample of time to edit all
