### ISSUE TITLE
[BUG] Dark mode functionality Error

### ISSUE THREAD

**Issue by Manishak798** [JAYESHBATRA/Virtuo-Learn#160]
### Description

I switched to dark mode, but as soon as I refreshed the website it automatically turned to light mode which does not look visually appealing, fixing this bug through JS with local storage would be helpful.

### Any additional information?

I am Manisha SWOC'24 Mentor, raising this issue for the contributors.

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea
- [ ] I am willing to work on this issue (optional)
- [ ] I am a SWOC'24 contributor
- [ ] I am an IWOC 2.0 contributor

**Comment by ROSHNEEGOUDA** [comment]
@Manishak798 Please assign me this issue (under SWOC'24).

**Comment by Manishak798** [comment]
> @Manishak798 Please assign me this issue (under SWOC'24).

I am a Mentor and not a project admin. Only admins can assign this to you.

**Comment by ROSHNEEGOUDA** [comment]
@JAYESHBATRA Please assign this issue to me(under SWOC'24).
