### ISSUE TITLE
[Feature] Sticky NAV BAR and even spacing in Between NAV ELEMENTS

### ISSUE THREAD

**Issue by Manishak798** [JAYESHBATRA/Virtuo-Learn#161]
### Description

Making a sticky nav bar will ease the user to explore different routes of the website, and giving a restyling to it will make it more appealing to viewers. I am a **SWOC Mentor** and raising this issue for contributors.

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea 
- [ ] I am willing to work on this issue (optional)
- [ ] I am a SWOC'24 contributor
- [ ] I am an IWOC 2.0 contributor

**Comment by praptisharma28** [comment]
Assign me @Manishak798 under iwoc.

**Comment by Manishak798** [comment]
> Assign me @Manishak798 under iwoc.

Only the project admin can assign this to you, I am the Mentor but I don't have these rights.

**Comment by praptisharma28** [comment]
Assign me @JAYESH-BATRA under iwoc

**Comment by DrishnaTrivedi** [comment]
@JAYESHBATRA Please assign this issue. I am gssoc'24 contributor

**Comment by harshmishra19** [comment]
@JAYESHBATRA Please assign this issue to me under gssoc'24

**Comment by Swapnita06** [comment]
@JAYESHBATRA please assign this to me!...I can contribute efficiently.

**Comment by Divyanshi1002** [comment]
hey,
I am keen to contribute in this project under GSSOC'24 . I have knowledge in JavaScript, HTML,CSS .
