### ISSUE TITLE
[Feature] RE-Alingment of text boxes.

### ISSUE THREAD

**Issue by Manishak798** [JAYESHBATRA/Virtuo-Learn#162]
### Description

The text size and the whole text box can be redesigned so that it will look more appealing and will increase the readability. I am Creating this issue under SWOC'24 as a Mentor.

### Screenshots

![image](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/90680330/d1085d39-d808-4c02-b891-42eaab8fbf8f)

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea 
- [ ] I am willing to work on this issue (optional)
- [ ] I am a SWOC'24 contributor
- [ ] I am an IWOC 2.0 contributor

**Comment by praptisharma28** [comment]
Assign me @Manishak798 under iwoc.

**Comment by praptisharma28** [comment]
Assign me @JAYESH-BATRA under iwoc
@JAYESHBATRA

**Comment by ROSHNEEGOUDA** [comment]
@JAYESHBATRA please assign this to me(SWOC 24).
