### ISSUE TITLE
[Feature] : Make the navbar translucent

### ISSUE THREAD

**Issue by mansi1309** [JAYESHBATRA/Virtuo-Learn#170]
### Description

what i propose is that we can make the navbar translucent giving it a glossy glass pane effect along with little border shadows at the bottom
and little bit darkened as well to make the navbar contents stand out.

Please assign this issue to me . I would like to work on it.

### Screenshots

![image](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/133951716/1b4d172b-0c98-472f-9a75-b41a5109771f)

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea 
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor
- [ ] I am an IWOC 2.0 contributor

**Comment by JAYESHBATRA** [comment]
Also, make it sticky and make NavBar changes on all pages, not just on the homePage. As you will need to change the navbar on all the pages, I am assigning the issue to the Hard Category.

**Comment by Swapnita06** [comment]
@JAYESHBATRA sr should i start it?

**Comment by JAYESHBATRA** [comment]
@Swapnita06 Yes go ahead

**Comment by Swapnita06** [comment]
Sure Sir...Thank you

**Comment by Swapnita06** [comment]
@JAYESHBATRA Sir please review  the changes !
