### ISSUE TITLE
[FIX] The Home button at the home page doesn't change color while hovering

### ISSUE THREAD

**Issue by AmitBiswas1402** [JAYESHBATRA/Virtuo-Learn#177]
The Home button on the home page doesn't change colour while hovering meanwhile the other pages' buttons change colours while hovering see below 

https://github.com/JAYESHBATRA/Virtuo-Learn/assets/115923314/8ffe967a-94b7-4f8a-acdb-d331944e47bf

**Comment by AmitBiswas1402** [comment]
Hi @JAYESHBATRA this project is not cloning to my local machine sadly ;( reassign it and give it to @FazeenIjaz

**Comment by FazeenIjaz** [comment]
@JAYESHBATRA Can i work on it?

**Comment by FazeenIjaz** [comment]
@JAYESHBATRA I raised a PR for this issue.Please check it out
