### ISSUE TITLE
In social media section twitter logo is not showing.

### ISSUE THREAD

**Issue by gauravsingh1281** [JAYESHBATRA/Virtuo-Learn#183]
### Description

In the social media section, the Twitter logo is not showing properly. It is positioned in the wrong direction.

### Screenshots
<img width="960" alt="Screenshot 2024-02-12 024536" src="https://github.com/JAYESHBATRA/Virtuo-Learn/assets/85905403/46ccec50-dd3e-4740-ae0d-d1d85fcfe6be">

<img width="956" alt="Screenshot 2024-02-12 023825" src="https://github.com/JAYESHBATRA/Virtuo-Learn/assets/85905403/0e258052-e236-477c-9234-485f373e4176">

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor
- [ ] I am an IWOC 2.0 contributor

**Comment by gauravsingh1281** [comment]
@JAYESHBATRA Please assign this issue to me under the SWOC 24 label.

**Comment by Nitinshukla88** [comment]
Hey @gauravsingh1281 Please elaborate how to reproduce this bug.

**Comment by JAYESHBATRA** [comment]
@gauravsingh1281 Kindly share more details on how to produce the bug.

**Comment by gauravsingh1281** [comment]
<img width="960" alt="Screenshot 2024-02-18 005003" src="https://github.com/JAYESHBATRA/Virtuo-Learn/assets/85905403/5a2b6f36-7694-4b11-bbcf-fd93e6d79b0c">



### Hii @JAYESHBATRA we can solve this bug by replacing the width value to 100%.
