### ISSUE TITLE
Adding icons .

### ISSUE THREAD

**Issue by Soumya6Tiwari** [JAYESHBATRA/Virtuo-Learn#190]
### Description

Adding icons for the components in the navbar such as for quizzes, simulations, about us etc.

### Screenshots

![Screenshot (1274)](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/117037441/2f56bfde-9f45-4001-b4f1-cdda25f01164)

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea 
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor
- [X] I am an IWOC 2.0 contributor

**Comment by Soumya6Tiwari** [comment]
@JAYESHBATRA  kindly assign me this issue under swoc 24

**Comment by Soumya6Tiwari** [comment]
@JAYESHBATRA Kindly assign me this issue.

**Comment by Gokilp** [comment]
please assign to me #gssoc24
