### ISSUE TITLE
[BUG] Footer not responsive in mobile view

### ISSUE THREAD

**Issue by Ankitapanda25** [JAYESHBATRA/Virtuo-Learn#198]
### Description

<img width="176" alt="GSSOC'24" src="https://github.com/JAYESHBATRA/Virtuo-Learn/assets/123666302/59978238-0da5-4e71-bb9c-76b83523f8d6">

The contents of the footer overflows in the mobile view. 

Please allow me to work on this issue under GSSOC'24

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSOC'24 contributor

**Comment by Karthikeyan1508** [comment]
@Ankitapanda25 I would like fix this bug under GSSoC'24. Could you please assign me with this bug & add the GSSoC label.

**Comment by Ankitapanda25** [comment]
@JAYESHBATRA I have created a pull request that fixes this issue. Kindly review it and give your feedback. And also please label it under GSSOC'24
