### ISSUE TITLE
[Feature]: Adding dark mode

### ISSUE THREAD

**Issue by maadi7** [JAYESHBATRA/Virtuo-Learn#20]
### Description

To enhance user expierence we can add dark theme.

### Screenshots

N/A

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea 
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'23 contributor

**Comment by anamithrak15** [comment]
I would like to contribute on this issue. Please assign this to me under swoc'24.

**Comment by JAYESHBATRA** [comment]
@maadi7 Are you working on it ?

**Comment by maadi7** [comment]
hii @JAYESHBATRA, sorry for the delay. actually I was busy with my college assignments for past few days, I will start working on it from tommorow for sure.

**Comment by maadi7** [comment]
hii @JAYESHBATRA, I am sorry but I am busy with my college work, if anyone else want to work on this please assign it to him/her. sorry once again for the inconvenience.

**Comment by JAYESHBATRA** [comment]
@anamithrak15 I have assigned this issue to you.

**Comment by anamithrak15** [comment]
Thank you
