### ISSUE TITLE
Non responsive Navbar

### ISSUE THREAD

**Issue by paulkrishanu4** [JAYESHBATRA/Virtuo-Learn#203]
### Description

navbar is responsive only in home page and for all other pages navbar is not responsive. I want to fix it.

### Screenshots

https://github.com/JAYESHBATRA/Virtuo-Learn/assets/169196836/046c17be-0b09-484b-9e13-d4a3ffae091a

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSOC'24 contributor

**Comment by paulkrishanu4** [comment]
I can fix this bug assign me

**Comment by AshishKumarSamantaray** [comment]
i can fix this please assign me for the same

**Comment by unstoppableayush** [comment]
Can I work on this, fixing the navbar as well as responsive?
