### ISSUE TITLE
[BUG] Adding home button.

### ISSUE THREAD

**Issue by yashi-15** [JAYESHBATRA/Virtuo-Learn#22]
### Description

I want to add the "Home" page button in navigation bar.
While navigating to other pages the home page gets lost, although the home page can be accessed by clicking on the logo but adding that in navigation bar would surely make the website more user-friendly.

### Any additional information?

I am a SWOC'24 contributor, assign this issue to me under SWOC'24 label.

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea
- [X] I am willing to work on this issue (optional)
- [ ] I am a SWOC'23 contributor

**Comment by subhasou26** [comment]
@yashi-15 I want to fix the issue can you assign it to me? I assure I can solve it

**Comment by JAYESHBATRA** [comment]
@subhasou26 currently @yashi-15 is working on this issue. If she is not able to resolve the issue then I will assign the issue to you. Feel free to raise any other issue in the repository and I will assign the issue to you.
