### ISSUE TITLE
[BUG] Navbar of the video player page is not in the default style.

### ISSUE THREAD

**Issue by Shubham-1068** [JAYESHBATRA/Virtuo-Learn#223]
### Description

- The styling of the navbar in the video player section of the Videos section is not in the default styling being used everywhere.

### Screenshots :-
- Default style of the navbar (being used everywhere) :-

 ![Screenshot 2024-05-12 122646](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/161105520/514f0d0a-2184-4987-9948-8c3f9368737c)

- The navbar where the default style is not being followed :- 

  
 ![Screenshot 2024-05-12 122714](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/161105520/07cce73e-7a06-490b-a1cf-8076a1a931f4)

**So, please allow me to work on this issue under GSSOC'24.**

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSOC'24 contributor

**Comment by alishasingh06** [comment]
please assign this issue to me
