### ISSUE TITLE
[Feature] Typography effect with the main page

### ISSUE THREAD

**Issue by AshishKumarSamantaray** [JAYESHBATRA/Virtuo-Learn#225]
### Description

Since you are just appending words with LEARN in the front page, we can use typography effect where the word gets typed along with learn and then backspaced and again a new word is typed as the section provided in ss below. Please assign me for the same

### Screenshots

![SPECTASTYLE - Brave 5_12_2024 4_05_24 PM](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/121350516/a29e50f8-ac23-407d-bbba-3bbb0c61a7b6)

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea 
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSOC'24 contributor

**Comment by saumyajainnn** [comment]
I would like to work on this issue.. please assign it to me
