### ISSUE TITLE
[BUG] Dark mode is not synced across all pages

### ISSUE THREAD

**Issue by tat-tvam-asii** [JAYESHBATRA/Virtuo-Learn#232]
### Description

The dark mode theme is not synced across all pages.I would make changes so that when dark mode is selected, it si synced across all pages of the website.
@JAYESHBATRA Please assign this to me under GSSOC'24

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSOC'24 contributor

**Comment by JAYESHBATRA** [comment]
@tat-tvam-asii  I've assigned you this issue under #148 . Therefore, I'll be closing this particular issue now. Thanks!
