### ISSUE TITLE
[Feature] Justification of the text .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [JAYESHBATRA/Virtuo-Learn#237]
### Description

I think if the text is justified from both the sides then it may increase the user experience .

### Screenshots

![Screenshot 2024-05-13 200638](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/118350936/c97eff36-ed58-4e9e-984b-29948c2ef185)

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea 
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSOC'24 contributor

**Comment by Ayushmaanagarwal1211** [comment]
Thanks for Assigning i will send PR today .

**Comment by tulikaa25** [comment]
i want to work on this issue. please assign it to me @JAYESHBATRA
