### ISSUE TITLE
header in quizzes 

### ISSUE THREAD

**Issue by NitinChakrawarti** [JAYESHBATRA/Virtuo-Learn#239]
### Description

header in  quizzes is not responsive it is not visible completely. In mobile devices

### Screenshots

![Screenshot 2024-05-13 201620](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/149225785/a93a29b9-6082-4335-8787-9d056597fc9f)

![Screenshot 2024-05-13 201838](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/149225785/e42ac92d-6584-492c-b63b-66a8a626ca76)

### Any additional information?

I can make it responsive for every device 

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSOC'24 contributor

**Comment by JAYESHBATRA** [comment]
@NitinChakrawarti This appears to be a duplicate issue that is already being addressed under #248 . Thank you for bringing it to our attention.
