### ISSUE TITLE
[Feature] Add More 3D Visualizations to the website [Contributors Needed Urgently]

### ISSUE THREAD

**Issue by JAYESHBATRA** [JAYESHBATRA/Virtuo-Learn#24]
### Description

Currently there are only 4 3D Visulaizations. We need to add more 3D Visualizations in the website. This enhancement is of Hard Category. 

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea 
- [ ] I am willing to work on this issue (optional)
- [ ] I am a SWOC'23 contributor

**Comment by sidharth2829** [comment]
I have completed all the requirements and gone through the repo. Please assign this issue to me under SWOC'24.
