### ISSUE TITLE
[BUG] Dark mode not working for every page 

### ISSUE THREAD

**Issue by pandeyji711** [JAYESHBATRA/Virtuo-Learn#244]
### Description

the dark mode is only work in home page it get light mode when visit to other page
please assign this issue to me in Gssoc2024 ,bug,

### Screenshots

![Screenshot 2024-05-14 141442](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/154527778/4e0290e1-2be4-44c5-b4f7-1cef62dfa01d)
![Screenshot 2024-05-14 141456](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/154527778/1c2f237a-2620-43a3-9e78-a3f3da253c2c)

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSOC'24 contributor

**Comment by pandeyji711** [comment]
@JAYESHBATRA please assign this to me under Gssoc 2024

**Comment by JAYESHBATRA** [comment]
@pandeyji711 This particular issue is already being addressed under #148 . Therefore, it seems to be a duplicate. Thank you for your attention to this matter.
