### ISSUE TITLE
[Feature] The plans templets are not animated when we are hovering it

### ISSUE THREAD

**Issue by subhasou26** [JAYESHBATRA/Virtuo-Learn#25]
### Description

When we hover over the plans there are no animation effects it looks like ancient factions. I can add suitable animation to it and the box will pop up and its looks nice 

### Screenshots

![image](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/83156210/e5c1d061-1481-49b5-9190-32fc3982e62d)

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea 
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'23 contributor

**Comment by subhasou26** [comment]
can you assigned to me?

**Comment by subhasou26** [comment]
after forking the repo when I am cloning it gives me an error can I download it in the zip file?
![image](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/83156210/7c55abe6-b778-41be-afb6-b4616beec6d8)

**Comment by abcd-aakarsh** [comment]
please assign me this issue
