### ISSUE TITLE
[Feature] Changing font

### ISSUE THREAD

**Issue by harikasayani** [JAYESHBATRA/Virtuo-Learn#256]
### Description

I am GSSOC'24 Contributor.
I want to change the font present in the web page.
Please assign this task to me.

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea 
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSOC'24 contributor

**Comment by JAYESHBATRA** [comment]
No need @harikasayani
