### ISSUE TITLE
[Feature] Enhancing text

### ISSUE THREAD

**Issue by Jhalak1225** [JAYESHBATRA/Virtuo-Learn#258]
### Description

I want to enhance the text in the below image.

### Screenshots

![steps](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/152611354/f78d529f-4d59-493d-b38e-cc2d4765203e)

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea 
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSOC'24 contributor

**Comment by JAYESHBATRA** [comment]
@Jhalak1225 This issue has been fixed now.
