### ISSUE TITLE
about us page need styling

### ISSUE THREAD

**Issue by ishaa18** [JAYESHBATRA/Virtuo-Learn#282]
### Description

the about us page shows paragraphs but it is not styled and looks boring.

### Screenshots

![Screenshot (38)](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/145281412/c639ed66-8c88-4984-a4a8-e5c8a74edd0a)
the given paragraphn can be converted to cards and can be styled.

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea 
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSOC'24 contributor

**Comment by rounakdey6** [comment]
Please assign this work to me
