### ISSUE TITLE
[Feature] Enhancing Our Product section by adding cards and attractive effects/annimation

### ISSUE THREAD

**Issue by Husan7** [JAYESHBATRA/Virtuo-Learn#292]
### Description
Hii sir , I want to work on this issue.
We can add cards in  our product section and also links are available in this cards
It makes our product section more attractive 
It is responsive effect 

https://github.com/JAYESHBATRA/Virtuo-Learn/assets/162671639/0295a6db-9c38-4005-a31b-7039c878e23c

 please assign me this issue .

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea 
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSOC'24 contributor

**Comment by JAYESHBATRA** [comment]
@Husan7 No need
