### ISSUE TITLE
[BUG] Testimonials and Navbar colliding issue

### ISSUE THREAD

**Issue by Gauranshgoel123** [JAYESHBATRA/Virtuo-Learn#293]
### Description

On scrolling down when we go to to the testimonials section, the cards overlap with the above navbar

### Screenshots

![image](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/121503835/ad59b4fa-8dfa-45d3-af4a-bc2c15f4eab8)

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSOC'24 contributor

**Comment by Gauranshgoel123** [comment]
please assign me this @JAYESH-BATRA

**Comment by JAYESHBATRA** [comment]
@Gauranshgoel123 Duplicate issue
