### ISSUE TITLE
[Feature] SIDE NAVBAR OF SOCIALS

### ISSUE THREAD

**Issue by Gauranshgoel123** [JAYESHBATRA/Virtuo-Learn#296]
### Description

currently this is the styling but it's styling can be made better like this

please assign me this

### Screenshots

currently:
![image](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/121503835/29b4be83-154f-4651-9b76-f99a81b111c7)

we can add the same social icons
i am just giving example of css effect that can be done

![image](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/121503835/d5d4f7e2-2cdd-4be0-8f7f-650b1622ac17)

![image](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/121503835/277e86ee-b954-49cb-b193-6fe60b9797c6)

![image](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/121503835/4c74f182-cd48-464a-967a-7888baa52540)

![image](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/121503835/ce0664cc-ae4b-406c-87fb-7b9ae90dc81f)

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea 
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSOC'24 contributor

**Comment by JAYESHBATRA** [comment]
@Gauranshgoel123 no need.
