### ISSUE TITLE
[Feature] WhiteSpace between steps is not equal. 

### ISSUE THREAD

**Issue by abcd-aakarsh** [JAYESHBATRA/Virtuo-Learn#30]
### Description

WhiteSpace between all the steps should be equal it will look good.

### Screenshots

![Screenshot (41)](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/133818110/7f1d4a3c-93b3-49b5-80fe-031f30bd6fdb)
![Screenshot (40)](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/133818110/cd509631-446b-4766-af0b-cfb77930f06b)

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea 
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'23 contributor

**Comment by abcd-aakarsh** [comment]
please assign me this issue

**Comment by Govind516** [comment]
is the issue still open ?
