### ISSUE TITLE
[BUG]: Footer isn't responsive.

### ISSUE THREAD

**Issue by nagalakshmi08** [JAYESHBATRA/Virtuo-Learn#324]
### Description

The footer is not responsive on smaller screens.

### Screenshots

![image](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/121669832/558be63f-781b-429f-b317-8748a1e0af46)

### Any additional information?

Please assign me this issue , I would like to contribute to this project under GSSoC'24.

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSOC'24 contributor

**Comment by SujalRaunak** [comment]
@JAYESHBATRA Sir, Can I fix this issue.
