### ISSUE TITLE
[Feature] <On dark mode the icon simulation on home page is not visible.>

### ISSUE THREAD

**Issue by Unknownmaster0** [JAYESHBATRA/Virtuo-Learn#325]
### Description

Switching the website to dark mode, the small icon of the simulation is not visible. It goes submerged in a dark color. 
It needs a slight change in the styling section, can you please assign this task to me? 

### Screenshots

![image](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/117724228/89b0f6b3-efb8-4df4-aa1f-0df82fcce0e6)
When in light mode.
![image](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/117724228/3c5364d5-f8aa-4b86-b2c4-9c17d31d204b)
When in dark mode.

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea 
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSOC'24 contributor

**Comment by DonaldReddy** [comment]
Issue no #274 address the same issue
