### ISSUE TITLE
[Style]: Enhance Scrollbar Styling for Improved Aesthetics

### ISSUE THREAD

**Issue by harmeetsingh11** [JAYESHBATRA/Virtuo-Learn#34]
### Description:
The current scrollbar styling on certain pages appears basic and defaults to the browser's default design. This issue aims to improve the visual appeal by implementing a more customized and aesthetically pleasing scrollbar style across the application.

### Tasks:
1. Research and choose an appropriate custom scrollbar design that aligns with the overall UI/UX of the application.
2. Implement the selected custom scrollbar design using CSS to replace the default browser scrollbar.
3. Ensure that the custom styling is consistent across different browsers for a cohesive user experience.
4. Test the scrollbar functionality to guarantee that the customization does not impact scrolling behavior negatively.

### Additional Information:
- Consider user feedback and preferences in selecting the custom scrollbar design.
- Aim for a design that complements the overall visual theme of the application.
- Take into account accessibility considerations to ensure the custom styling does not hinder usability.

### Acceptance Criteria:
- The scrollbar on relevant pages should exhibit the custom styling as per the chosen design.
- The custom scrollbar should be visually appealing and enhance the overall user interface.
- Scroll functionality remains smooth and consistent across different browsers.

By addressing this issue, we aim to enhance the visual aesthetics of the application and provide users with a more polished and enjoyable scrolling experience.

### Record 

- [x] I agree to follow this project's Code of Conduct 
- [x] I'm a SWOC 4.0 contributor
- [x] I want to work on this issue

**Comment by JAYESHBATRA** [comment]
@harmeetsingh11 This issue is already been taken under issue #18 . Kindly wait if it is not resolved then I will assign it to you.
