### ISSUE TITLE
[BUG] Solution button is not working

### ISSUE THREAD

**Issue by Shu12388y** [JAYESHBATRA/Virtuo-Learn#4]
### Description

The solution button is not working, not showing the solution of the quiz

### Screenshots

![Screenshot (116)](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/91714143/23213341-7e3b-49f0-a542-7d07841faaf2)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'23 contributor

**Comment by JAYESHBATRA** [comment]
The solutions components has not been designed yet. You will have to design it from scratch . Should I assign you this issue ?
