### ISSUE TITLE
[Bug] Outdated Twitter Logo

### ISSUE THREAD

**Issue by ayushichoudhary-19** [JAYESHBATRA/Virtuo-Learn#40]
### Description

**Issue Description:**
The website currently uses an outdated Twitter logo. To maintain a modern and consistent look, I suggest updating the Twitter logo to the latest version.

### Screenshots

![image](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/73214455/78d286ff-6c26-4d01-bcc8-9f3de0c3b277)

### Any additional information?

I am willing to contribute and address this issue. Could someone please assign it to me?

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'23 contributor

**Comment by anamithrak15** [comment]
I would like to contribute on this issue. Please assign this to me under swoc'24.

**Comment by GhoshAditi** [comment]
i would like to contribute please assign me this

**Comment by JAYESHBATRA** [comment]
@ayushichoudhary-19 Are you working on it ?

**Comment by Nandini80** [comment]
@JAYESHBATRA Please assign me this issue

**Comment by 29deepanshutyagi** [comment]
kindly assign me this issue @JAYESHBATRA , i want to work on this issue
