### ISSUE TITLE
[Feature] Migrate to Tailwind CSS [Contributors Needed Urgently]

### ISSUE THREAD

**Issue by JAYESHBATRA** [JAYESHBATRA/Virtuo-Learn#50]
### Description

Currently CSS is being used in the codebase. We want to migrate to Tailwind CSS. Separate pull requests will be made for each section that is converted. We need this on urgent basis and only contributors who have worked with Tailwind CSS should contribute. 

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea 
- [ ] I am willing to work on this issue (optional)
- [ ] I am a SWOC'23 contributor

**Comment by jiteshpahwa04** [comment]
Hey! I can work with this issue, I have made most of my projects using Tailwind CSS. You can assign it to me.

**Comment by jiteshpahwa04** [comment]
Just a question, can I add npm to the repo ?
It would make adding global css about scrollbar, etc. easier.
