### ISSUE TITLE
[Feature] Change Twitter logo to X

### ISSUE THREAD

**Issue by blindaks** [JAYESHBATRA/Virtuo-Learn#66]
### Description

We can change Twitter logo to X.

### Screenshots

<img width="56" alt="image" src="https://github.com/JAYESHBATRA/Virtuo-Learn/assets/128223364/163ef97e-6717-4942-9dde-c71f37bc50d3">

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea 
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'23 contributor

**Comment by JAYESHBATRA** [comment]
@blindaks This issue is a duplicate one.
