### ISSUE TITLE
[BUG] Fix uneven gap

### ISSUE THREAD

**Issue by blindaks** [JAYESHBATRA/Virtuo-Learn#67]
### Description

There is uneven gap between the steps section.

### Screenshots

<img width="999" alt="image" src="https://github.com/JAYESHBATRA/Virtuo-Learn/assets/128223364/22aa433c-b023-4ccd-91b2-1562f116a863">

<img width="955" alt="image" src="https://github.com/JAYESHBATRA/Virtuo-Learn/assets/128223364/5cce2c06-c11d-44ba-ba2a-a9c0071ce049">

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'23 contributor

**Comment by abcd-aakarsh** [comment]
this is already in issues and i m working on it
