### ISSUE TITLE
UI of Home Page

### ISSUE THREAD

**Issue by CodeByRajeev** [JAYESHBATRA/Virtuo-Learn#72]
**Enhancement of The Whole color of the Home Page & Footer.**

This issue is simple but it create a lot of enhancement to the whole project.

Take a look at the differences before and after making changes:

**Before:** 

![Home color before 1](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/112249927/536216b9-cc7b-41c8-9daf-934078067765)

**After:** 

![Home color after 1](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/112249927/4fc94216-0699-46b9-83a3-d70c19bc9875)

**Comment by CodeByRajeev** [comment]
@JAYESHBATRA sir, This issue is just a try but I hope it makes a great impact. So just look at the screen shot and assign me the issue if you really feel like meaningful improvement.

**Comment by Nitinshukla88** [comment]
Assign this issue to me @JAYESHBATRA

**Comment by CodeByRajeev** [comment]
> Assign this issue to me @JAYESHBATRA 

Hey @Nitinshukla88 , I hope you understand that I have raised the issue and also the coding part has been done. I am waiting for the issue to be assigned. I kindly request you to work on any better issue.

**Comment by JAYESHBATRA** [comment]
@CodeByRajeev No need at all. The design you are proposing did not look very appealing so I don't think you should proceed.
