### ISSUE TITLE
[Feature] Add Scroll To Top Button only on Home Page

### ISSUE THREAD

**Issue by JAYESHBATRA** [JAYESHBATRA/Virtuo-Learn#73]
### Description

Need to add scroll to top button on the home page of the website.

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea 
- [ ] I am willing to work on this issue (optional)
- [ ] I am a SWOC'23 contributor

**Comment by anshulkansal04** [comment]
Hey @JAYESHBATRA , Can You Please Assign me this Issue under SWOC S4.
Checklist
- [x] I have starred the repository
- [x]  I have checked the existing issues
- [x]  I have read the discussion tab thoroughly and got the project idea
- [x]  I am willing to work on this issue
- [x]  I am a SWOC'24 contributor
