### ISSUE TITLE
[Feature] add a doubt submission form UI in doubt section

### ISSUE THREAD

**Issue by Komal73** [JAYESHBATRA/Virtuo-Learn#75]
### Description

the doubt engine page does not have any form to submit the doubt. I want to create a form UI to make user interaction easy.

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea 
- [X] I am willing to work on this issue (optional)
- [ ] I am a SWOC'23 contributor

**Comment by Komal73** [comment]
@JAYESHBATRA Kindly assign this issue under SWOC 24

**Comment by JAYESHBATRA** [comment]
No Need
