### ISSUE TITLE
[Feature] improve footer section by adding contact and help options

### ISSUE THREAD

**Issue by Komal73** [JAYESHBATRA/Virtuo-Learn#77]
### Description

to add a small about section, contact info, and help section in the footer to make options available easily for user's convenience.

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea 
- [X] I am willing to work on this issue (optional)
- [ ] I am a SWOC'23 contributor

**Comment by Komal73** [comment]
@JAYESHBATRA kindly assign this issue under SWOC 24

**Comment by Komal73** [comment]
@AbhineshJha i am working on this issue

**Comment by Bhupendra3444** [comment]
hey @JAYESHBATRA please assign me this issue under iwoc.
