### ISSUE TITLE
Modifying buttons.

### ISSUE THREAD

**Issue by yashi-15** [JAYESHBATRA/Virtuo-Learn#87]
### Description

The buttons "Previous" and "Next" should be replaced with "+" and "-" buttons as they increase or decrease the value in Orbital configuration simulation. This would make it more user friendly.

I would like to work on this issue. Kindly assign it to me under SWOC. Thankyou!

### Screenshots

![Screenshot (203)](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/132138302/48a6b4fb-63e7-4b37-881b-80c001018865)

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

**Comment by JAYESHBATRA** [comment]
No need.
