### ISSUE TITLE
[BUG] The Up Arrow is not working.

### ISSUE THREAD

**Issue by Nitinshukla88** [JAYESHBATRA/Virtuo-Learn#97]
### Description

When you scroll down and reach to end of the page and try to go up by clicking on up arrow, then it is not responding as you can see in the screenshot below.

### Screenshots

![Screenshot (7)](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/143546627/b1a87fbb-0c01-441d-b267-9c94b04529a1)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

**Comment by Nitinshukla88** [comment]
@JAYESHBATRA Validate the issue and Assign it to me.

**Comment by shakti177** [comment]
Can You Please Assign it to Me?
